In [1]:
l = range(1000)         #tut-1 : codebasics
l

range(0, 1000)

In [2]:
import numpy as np
import time
import sys

In [3]:
print(sys.getsizeof(5)*len(l))

28000


In [4]:
arr = np.arange(1000)
print( arr.size*arr.itemsize)

4000


In [7]:
SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

#calculating time taken for list to process

start = time.time()
result =  [ (x+y) for x,y in zip(l1,l2) ]
print("python list took: " ,(time.time()-start)*1000 )

#calculating time taken for numpy array to process

start = time.time()
result = a1+a2
print("numpy array took: " ,(time.time()-start)*1000 )


python list took:  82.92317390441895
numpy array took:  7.762908935546875


In [8]:
b1 = np.array([1,2,3])
b2 = np.array([2,4,6])

In [13]:
b1+b2

array([3, 6, 9])

In [10]:
b1-b2

array([-1, -2, -3])

In [11]:
b1/b2

array([0.5, 0.5, 0.5])

In [14]:
b1*b2

array([ 2,  8, 18])

In [26]:
#multi-dimensional array             #tut-2 : codebasics

a = np.array([ [1,2],[3,4],[5,6] ])
print(a.ndim)                                  #returns dimension
print(a.itemsize)                              #returns size
print(a.dtype)                                 #returns data type
print(a.size)
print(a.shape)

2
4
int32
6
(3, 2)


In [27]:
a = np.array([ [1,2],[3,4],[5,6] ] , dtype=np.float64 )
print(a.ndim)                                  #returns dimension
print(a.itemsize)
print(a.dtype)

2
8
float64


In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.arange(1,5)

array([1, 2, 3, 4])

In [31]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [33]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [35]:
a = np.array([
[1,2],
[3,4],
[5,6]
    ])

In [36]:
a.shape

(3, 2)

In [37]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
a.ravel()                   

array([1, 2, 3, 4, 5, 6])

In [40]:
#none of these function alter the orginal array, it returns a new array

In [41]:
#mathematical func :

a.min()

1

In [42]:
a.max()

6

In [43]:
a.sum()

21

In [44]:
a.sum(axis=0)

array([ 9, 12])

In [45]:
a.sum(axis=1)

array([ 3,  7, 11])

In [46]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [47]:
np.std(a)

1.707825127659933

In [48]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [49]:
a+b

array([[ 6,  8],
       [10, 12]])

In [50]:
a-b

array([[-4, -4],
       [-4, -4]])

In [51]:
#indexing & slicing                   #tut-3 : codebasics

n = [6,7,8]
n[0:2]

[6, 7]

In [52]:
a = np.array([2,4,6,8])
a[0:3]

array([2, 4, 6])

In [54]:
a = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
a[1,2]

6

In [56]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a[0:2,1]

array([2, 5])

In [58]:
a[-1]

array([7, 8, 9])

In [60]:
a[1:3,-1]

array([6, 9])

In [61]:
a[-1,0:2]

array([7, 8])

In [62]:
a[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [67]:
for cell in a.flat :
    print(cell)

1
2
3
4
5
6
7
8
9


In [68]:
#stacking array

a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [69]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [70]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [71]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [72]:
#split

c = np.arange(30).reshape(2,15)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [73]:
np.hsplit(c,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [74]:
np.vsplit(c,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [76]:
#boolean array :

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [80]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [83]:
a[b]=-1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [84]:
#iterate numpy array using nditer                     #tut-4 : codebasics

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
for x in a :
    for y in x :
        print(y)

0
1
2
3
4
5
6
7
8
9
10
11


In [86]:
for x in a.flat :
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [87]:
for x in np.nditer(a,order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [88]:
for y in np.nditer(a,order='F'):
    print(y)

0
4
8
1
5
9
2
6
10
3
7
11


In [89]:
for x in np.nditer(a,order='F', flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [90]:
for x in np.nditer(a, op_flags=['readwrite']) :
    x[...] = x*x

In [91]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [96]:
b = np.arange(3,15,5).reshape(3,1)
b

array([[ 3],
       [ 8],
       [13]])

In [97]:
for x,y in np.nditer([a,b]) :
    print(x,y)

0 3
1 3
4 3
9 3
16 8
25 8
36 8
49 8
64 13
81 13
100 13
121 13
